server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: wg-tools-backend
  
  # 禁用数据库自动配置，避免启动失败
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# 日志配置
logging:
  level:
    com.wgtools: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 跨域配置（完全无限制）
cors:
  allowed-origin-patterns: "*"  # 允许所有来源访问
  allowed-methods: "*"  # 允许所有HTTP方法
  allowed-headers: "*"  # 允许所有请求头
  allow-credentials: true  # 允许携带凭证
  max-age: 3600
