server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: wg-tools-backend
  
  # 禁用数据库自动配置，避免启动失败
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# 日志配置
logging:
  level:
    com.wgtools: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 跨域配置
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:8081
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
